idf_component_register(
    SRCS
        "app_main.c"
        "lib/src/engine.c"
        "lib/src/helpers.c"
        "lib/src/init_wifi.c"
        "lib/src/data_queue.c"
        "lib/src/send.c"
        "lib/src/websocket.c"
    INCLUDE_DIRS
        "lib/include"
    REQUIRES
        esp_driver_ledc
        esp_http_server
)